#!/bin/sh
BLUE_PATH=/root/deploy/blue-www/
NPM_PATH=/usr/bin/npm
GIT_PATH=/usr/bin/git
GIT_WORK_TREE=/root/deploy/blue-www/ $GIT_PATH checkout -f
cd $BLUE_PATH
$NPM_PATH install
APP_PATH=/root/App
DOCKER=/usr/bin/docker
#Remove existing container if it exists
$DOCKER rm -f app
#Now remove the image
$DOCKER rmi ncsu-app
#Build the image from the Dockerfile
$DOCKER build -t ncsu-app .
$DOCKER run -p 50200:8080 -d --name app ncsu-app
$DOCKER logs app
#Pull from registery
$DOCKER pull localhost:5000/ncsu:latest
$DOCKER stop app
$DOCKER rm app
$DOCKER rmi localhost:5000/ncsu:current
$DOCKER tag localhost:5000/ncsu:latest localhost:5000/ncsu:current
$DOCKER run -p 50100:8080 -d --name app localhost:5000/ncsu:latest
