#!/bin/sh
GREEN_PATH=/root/deploy/green-www/
NPM_PATH=/usr/bin/npm
GIT_PATH=/usr/bin/git
GIT_WORK_TREE=/root/deploy/green-www/ $GIT_PATH checkout -f
cd $GREEN_PATH
$NPM_PATH install
APP_PATH=/root/App
DOCKER=/usr/bin/docker
#Remove existing container if it exists
$DOCKER rm -f app
#Now remove the image
$DOCKER rmi ncsu-app
#Build the image from the Dockerfile
$DOCKER build -t ncsu-app .
#Tag the image
$DOCKER tag -f ncsu-app localhost:5000/ncsu:latest
#push to the registery
$DOCKER push localhost:5000/ncsu:latest
$DOCKER run -p 50100:8080 -d --name app ncsu-app
$DOCKER logs app
#pull from registery
$DOCKER pull localhost:5000/ncsu:latest
$DOCKER stop app
$DOCKER rm app
$DOCKER rmi localhost:5000/ncsu:current
$DOCKER tag localhost:5000/ncsu:latest localhost:5000/ncsu:current
$DOCKER run -p 50100:8080 -d --name app localhost:5000/ncsu:latest
