FROM ubuntu:latest
MAINTAINER adtelhar@ncsu.edu

#Install Curl so that it can be used later
RUN apt-get -y install curl

#container1 is the name of the container which this container would be linked to after executing docker run using this image
CMD curl container1:9001
